allowBuilds:
  '@parcel/watcher': true
  bcrypt: true
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - nodemailer@9.0.1
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - bcrypt
  - sharp
  - unrs-resolver
