import dbConnect from "@/lib/dbConnect";
import Training from "@/models/Training";
import { verifyAdmin } from "@/utils/validator";
import { NextRequest, NextResponse } from "next/server";

const seedCourses = [
    {
        slug: "web-design",
        title: "Web Design",
        description: "Learn modern web design principles, responsive layouts, and user experience fundamentals.",
        detailedDescription: "Master the art of creating visually appealing and user-friendly websites. This comprehensive course covers HTML5, CSS3, responsive design, typography, color theory, and modern design frameworks.",
        tools: ["VS Code", "Figma", "Adobe Creative Suite", "Chrome DevTools"],
        prerequisites: "Basic computer knowledge",
        certification: "Industry-recognized certificate upon completion",
        published: true,
        packages: [{
            name: "6-Month Certificate",
            tier: "certificate",
            duration: "6 months",
            totalFee: 9000,
            offlineTotalFee: 15000,
            registrationFee: 3000,
            installmentAmount: 2000,
            installmentCount: 3,
            currency: "BDT",
            scheduleType: "both",
            modules: [
                { title: "HTML5 & CSS3 Fundamentals" },
                { title: "Responsive Web Design" },
                { title: "Typography & Color Theory" },
                { title: "CSS Frameworks (Bootstrap, Tailwind)" },
                { title: "Design Tools (Figma, Adobe XD)" },
                { title: "Portfolio Development" },
            ],
        }],
    },
    {
        slug: "web-development",
        title: "Web Development",
        description: "Master front-end and back-end development with modern frameworks and technologies.",
        detailedDescription: "Become a full-stack developer with expertise in both client-side and server-side technologies. Learn JavaScript, React, Node.js, databases, and deployment strategies.",
        tools: ["VS Code", "Node.js", "MongoDB", "Git", "Postman"],
        prerequisites: "Basic programming knowledge recommended",
        certification: "Full-Stack Developer Certificate",
        published: true,
        packages: [{
            name: "6-Month Certificate",
            tier: "certificate",
            duration: "6 months",
            totalFee: 9000,
            offlineTotalFee: 15000,
            registrationFee: 3000,
            installmentAmount: 2000,
            installmentCount: 3,
            currency: "BDT",
            scheduleType: "both",
            modules: [
                { title: "JavaScript ES6+ Fundamentals" },
                { title: "React.js & Component Architecture" },
                { title: "Node.js & Express.js" },
                { title: "Database Design (MongoDB, MySQL)" },
                { title: "API Development & Integration" },
                { title: "Version Control with Git" },
            ],
        }],
    },
    {
        slug: "graphic-design",
        title: "Graphic Design",
        description: "Create stunning visual designs using industry-standard tools and design principles.",
        detailedDescription: "Develop your creative skills in visual communication, branding, and digital design. Master Adobe Creative Suite and learn design principles that make your work stand out.",
        tools: ["Adobe Photoshop", "Adobe Illustrator", "Adobe InDesign", "Canva Pro"],
        prerequisites: "Creative mindset and basic computer skills",
        certification: "Professional Graphic Designer Certificate",
        published: true,
        packages: [{
            name: "6-Month Certificate",
            tier: "certificate",
            duration: "6 months",
            totalFee: 9000,
            offlineTotalFee: 15000,
            registrationFee: 3000,
            installmentAmount: 2000,
            installmentCount: 3,
            currency: "BDT",
            scheduleType: "both",
            modules: [
                { title: "Design Principles & Theory" },
                { title: "Adobe Photoshop Mastery" },
                { title: "Adobe Illustrator Techniques" },
                { title: "Brand Identity Design" },
                { title: "Print & Digital Media Design" },
                { title: "Portfolio Creation" },
            ],
        }],
    },
    {
        slug: "ui-ux-design",
        title: "UI-UX Design",
        description: "Design intuitive user interfaces and create exceptional user experiences.",
        detailedDescription: "Learn to create user-centered designs that are both beautiful and functional. Master user research, wireframing, prototyping, and usability testing.",
        tools: ["Figma", "Adobe XD", "Sketch", "InVision", "Miro"],
        prerequisites: "Basic design knowledge helpful",
        certification: "UI/UX Designer Professional Certificate",
        published: true,
        packages: [{
            name: "6-Month Certificate",
            tier: "certificate",
            duration: "6 months",
            totalFee: 9000,
            offlineTotalFee: 15000,
            registrationFee: 3000,
            installmentAmount: 2000,
            installmentCount: 3,
            currency: "BDT",
            scheduleType: "both",
            modules: [
                { title: "User Research & Analysis" },
                { title: "Wireframing & Prototyping" },
                { title: "UI Design Principles" },
                { title: "Interaction Design" },
                { title: "Usability Testing" },
                { title: "Design Systems" },
            ],
        }],
    },
    {
        slug: "digital-marketing",
        title: "Digital Marketing",
        description: "Learn digital marketing strategies, SEO, social media marketing, and analytics.",
        detailedDescription: "Master the digital marketing landscape with hands-on experience in SEO, social media marketing, content marketing, PPC advertising, and analytics.",
        tools: ["Google Analytics", "Google Ads", "Facebook Business Manager", "SEMrush"],
        prerequisites: "Basic internet and social media knowledge",
        certification: "Digital Marketing Professional Certificate",
        published: true,
        packages: [{
            name: "6-Month Certificate",
            tier: "certificate",
            duration: "6 months",
            totalFee: 9000,
            offlineTotalFee: 15000,
            registrationFee: 3000,
            installmentAmount: 2000,
            installmentCount: 3,
            currency: "BDT",
            scheduleType: "both",
            modules: [
                { title: "Digital Marketing Fundamentals" },
                { title: "Search Engine Optimization (SEO)" },
                { title: "Social Media Marketing" },
                { title: "Content Marketing Strategy" },
                { title: "Google Ads & Facebook Ads" },
                { title: "Analytics & Performance Tracking" },
            ],
        }],
    },
    {
        slug: "cms-development",
        title: "CMS Development",
        description: "Build and customize content management systems using popular platforms.",
        detailedDescription: "Learn to develop and customize content management systems. Master WordPress, Drupal, and modern headless CMS solutions for dynamic website development.",
        tools: ["WordPress", "PHP", "MySQL", "Strapi", "VS Code"],
        prerequisites: "Basic web development knowledge",
        certification: "CMS Developer Certificate",
        published: true,
        packages: [{
            name: "6-Month Certificate",
            tier: "certificate",
            duration: "6 months",
            totalFee: 9000,
            offlineTotalFee: 15000,
            registrationFee: 3000,
            installmentAmount: 2000,
            installmentCount: 3,
            currency: "BDT",
            scheduleType: "both",
            modules: [
                { title: "CMS Fundamentals" },
                { title: "WordPress Development" },
                { title: "Custom Theme Creation" },
                { title: "Plugin Development" },
                { title: "Headless CMS (Strapi, Contentful)" },
                { title: "E-commerce Integration" },
            ],
        }],
    },
    {
        slug: "mern-stack-development",
        title: "MERN Stack Development",
        description: "Full-stack development with MongoDB, Express.js, React, and Node.js.",
        detailedDescription: "Become proficient in the MERN stack and build modern, scalable web applications. Learn MongoDB, Express.js, React, and Node.js with real-world projects.",
        tools: ["MongoDB", "Express.js", "React", "Node.js", "VS Code"],
        prerequisites: "JavaScript fundamentals required",
        certification: "MERN Stack Developer Certificate",
        published: true,
        packages: [{
            name: "6-Month Certificate",
            tier: "certificate",
            duration: "6 months",
            totalFee: 9000,
            offlineTotalFee: 15000,
            registrationFee: 3000,
            installmentAmount: 2000,
            installmentCount: 3,
            currency: "BDT",
            scheduleType: "both",
            modules: [
                { title: "MongoDB Database Design" },
                { title: "Express.js Server Development" },
                { title: "React.js Frontend Development" },
                { title: "Node.js Backend Programming" },
                { title: "Authentication & Authorization" },
                { title: "Deployment & DevOps" },
            ],
        }],
    },
    {
        slug: "basic-computer-and-ai-tools-training",
        title: "Basic Computer and AI Tools Training",
        description: "Master essential computer skills and modern AI tools for enhanced productivity.",
        detailedDescription: "Build foundational computer skills and learn to leverage AI tools for increased productivity. Perfect for beginners looking to enhance their digital literacy.",
        tools: ["Windows/Mac OS", "ChatGPT", "Google Workspace", "AI Writing Tools"],
        prerequisites: "No prior experience required",
        certification: "Digital Literacy Certificate",
        published: true,
        packages: [{
            name: "6-Month Certificate",
            tier: "certificate",
            duration: "6 months",
            totalFee: 9000,
            offlineTotalFee: 15000,
            registrationFee: 3000,
            installmentAmount: 2000,
            installmentCount: 3,
            currency: "BDT",
            scheduleType: "both",
            modules: [
                { title: "Computer Fundamentals" },
                { title: "Internet & Email Basics" },
                { title: "File Management & Organization" },
                { title: "AI Tools (ChatGPT, Claude, Gemini)" },
                { title: "Productivity AI Applications" },
                { title: "Digital Security & Privacy" },
            ],
        }],
    },
    {
        slug: "microsoft-office-tools-training",
        title: "Microsoft Office Tools Training",
        description: "Master Microsoft Office suite for professional productivity and efficiency.",
        detailedDescription: "Become proficient in Microsoft Office applications including Word, Excel, PowerPoint, and Outlook. Learn advanced features and automation techniques.",
        tools: ["Microsoft Word", "Excel", "PowerPoint", "Outlook", "Access"],
        prerequisites: "Basic computer knowledge",
        certification: "Microsoft Office Specialist Certificate",
        published: true,
        packages: [{
            name: "6-Month Certificate",
            tier: "certificate",
            duration: "6 months",
            totalFee: 9000,
            offlineTotalFee: 15000,
            registrationFee: 3000,
            installmentAmount: 2000,
            installmentCount: 3,
            currency: "BDT",
            scheduleType: "both",
            modules: [
                { title: "Microsoft Word Advanced" },
                { title: "Excel Formulas & Functions" },
                { title: "PowerPoint Presentation Design" },
                { title: "Outlook Email Management" },
                { title: "Access Database Basics" },
                { title: "Office Integration & Automation" },
            ],
        }],
    },
];

export const POST = async (req: NextRequest) => {
    try {
        await dbConnect();
        await verifyAdmin(req);

        const existing = await Training.countDocuments();
        if (existing > 0) {
            return NextResponse.json(
                { success: false, message: `Seed skipped — ${existing} courses already exist. Delete them first to re-seed.` },
                { status: 409 }
            );
        }

        const inserted = await Training.insertMany(seedCourses);
        return NextResponse.json(
            { success: true, message: `Seeded ${inserted.length} training courses.`, count: inserted.length },
            { status: 201 }
        );
    } catch (error) {
        console.error("Error seeding training courses:", error);
        return NextResponse.json({ success: false, message: "Internal Server Error" }, { status: 500 });
    }
};
