import dbConnect from "@/lib/dbConnect";
import Training from "@/models/Training";
import { verifyAdmin } from "@/utils/validator";
import { NextRequest, NextResponse } from "next/server";

const seedCourses = [
    // 1 ─ Web Design
    {
        slug: "web-design",
        title: "Web Design",
        description: "Learn modern web design principles, responsive layouts, and user experience fundamentals.",
        detailedDescription: "Master the art of creating visually appealing and user-friendly websites. This comprehensive course covers HTML5, CSS3, responsive design, typography, color theory, and modern design frameworks.",
        tools: ["VS Code", "Figma", "Adobe Creative Suite", "Chrome DevTools"],
        prerequisites: "Basic computer knowledge",
        certification: "Industry-recognized certificate upon completion",
        published: true,
        packages: [
            {
                name: "Foundation",
                tier: "certificate",
                duration: "6 months",
                totalFee: 12000,
                offlineTotalFee: 18000,
                registrationFee: 4000,
                installmentAmount: 2000,
                installmentCount: 4,
                currency: "BDT",
                scheduleType: "both",
                isPopular: false,
                isJobReady: false,
                outcomeStatement: "Build 3 real responsive websites and publish your portfolio online by the end of 6 months",
                idealForThisPackage: "Perfect for complete beginners, career-changers, and anyone who wants to start freelancing within 6 months",
                deliverables: [
                    "3 live, responsive portfolio websites",
                    "Figma source files for all design work",
                    "Documented codebase on GitHub",
                    "Industry-recognized 6-month certificate",
                ],
                modules: [
                    { title: "HTML5 & CSS3 Fundamentals", project: "Build a personal profile page from scratch" },
                    { title: "Responsive Web Design", project: "Convert a fixed desktop layout to mobile-first responsive" },
                    { title: "Typography & Color Theory" },
                    { title: "CSS Frameworks (Bootstrap, Tailwind)", project: "Recreate a real client homepage in Tailwind CSS" },
                    { title: "Design Tools (Figma, Adobe XD)" },
                    { title: "Portfolio Development", project: "Publish your 3-site portfolio to a live domain" },
                ],
            },
            {
                name: "Job-Ready Professional",
                tier: "job-ready",
                duration: "1 year",
                totalFee: 18000,
                offlineTotalFee: 25000,
                registrationFee: 6000,
                installmentAmount: 2000,
                installmentCount: 6,
                currency: "BDT",
                scheduleType: "both",
                isPopular: true,
                isJobReady: true,
                outcomeStatement: "Graduate with 6+ client-quality projects, real internship experience, and a job placement referral from Webtricker",
                idealForThisPackage: "For motivated learners who want a full-time design career or to freelance professionally within a year",
                deliverables: [
                    "6+ client-quality web design projects",
                    "Advanced Figma & Adobe Creative Suite proficiency",
                    "Real client internship (included)",
                    "Job placement support & referral",
                    "1-year Professional Certificate",
                    "LinkedIn profile review & optimization",
                ],
                modules: [
                    { title: "HTML5 & CSS3 Fundamentals", project: "Build a personal profile page from scratch" },
                    { title: "Responsive Web Design", project: "Convert a fixed desktop layout to mobile-first responsive" },
                    { title: "Typography & Color Theory" },
                    { title: "CSS Frameworks (Bootstrap, Tailwind)", project: "Recreate a real client homepage in Tailwind CSS" },
                    { title: "Design Tools (Figma, Adobe XD)" },
                    { title: "Portfolio Development", project: "Publish your 3-site portfolio to a live domain" },
                    { title: "Advanced CSS Animation & Interactions", project: "Build an animated agency landing page" },
                    { title: "Web Design Systems & Brand Guidelines", project: "Create a complete brand identity for a mock startup" },
                    { title: "Client Brief Handling & Freelance Business" },
                    { title: "Advanced Figma: Components & Auto Layout", project: "Design a multi-screen product app in Figma" },
                    { title: "Career Preparation & Portfolio Review" },
                    { title: "Internship (Real Client Project)" },
                ],
            },
        ],
    },

    // 2 ─ Web Development
    {
        slug: "web-development",
        title: "Web Development",
        description: "Master front-end and back-end development with modern frameworks and technologies.",
        detailedDescription: "Become a full-stack developer with expertise in both client-side and server-side technologies. Learn JavaScript, React, Node.js, databases, and deployment strategies.",
        tools: ["VS Code", "Node.js", "MongoDB", "Git", "Postman"],
        prerequisites: "Basic programming knowledge recommended",
        certification: "Full-Stack Developer Certificate",
        published: true,
        packages: [
            {
                name: "Foundation",
                tier: "certificate",
                duration: "6 months",
                totalFee: 12000,
                offlineTotalFee: 18000,
                registrationFee: 4000,
                installmentAmount: 2000,
                installmentCount: 4,
                currency: "BDT",
                scheduleType: "both",
                isPopular: false,
                isJobReady: false,
                outcomeStatement: "Build and deploy 2 real full-stack web apps — a task manager and a product catalog — and understand how modern web applications work end to end",
                idealForThisPackage: "Beginners and designers who want to start coding and ship real web apps within 6 months",
                deliverables: [
                    "Deployed task manager app with user authentication",
                    "Product catalog with search & filter functionality",
                    "REST API with documented endpoints",
                    "GitHub portfolio with 2 public projects",
                    "Full-Stack Developer Certificate",
                ],
                modules: [
                    { title: "JavaScript ES6+ Fundamentals", project: "Build an interactive quiz app" },
                    { title: "React.js & Component Architecture", project: "Build a task management UI with React" },
                    { title: "Node.js & Express.js", project: "Build a REST API for the task manager" },
                    { title: "Database Design (MongoDB, MySQL)", project: "Design the schema for a product catalog" },
                    { title: "API Development & Integration", project: "Connect your frontend to the backend API" },
                    { title: "Version Control with Git" },
                ],
            },
            {
                name: "Job-Ready Professional",
                tier: "job-ready",
                duration: "1 year",
                totalFee: 18000,
                offlineTotalFee: 25000,
                registrationFee: 6000,
                installmentAmount: 2000,
                installmentCount: 6,
                currency: "BDT",
                scheduleType: "both",
                isPopular: true,
                isJobReady: true,
                outcomeStatement: "Graduate with a deployed, client-grade full-stack application, real internship experience, and the skills to take on professional development projects",
                idealForThisPackage: "Committed learners who want to land a junior developer role or start taking freelance development projects within a year",
                deliverables: [
                    "1 deployed, client-grade full-stack application",
                    "Payment integration with SSLCommerz",
                    "Admin dashboard with role-based access control",
                    "Real internship project contribution",
                    "Job placement support",
                    "1-year Full-Stack Developer Certificate",
                ],
                modules: [
                    { title: "JavaScript ES6+ Fundamentals", project: "Build an interactive quiz app" },
                    { title: "React.js & Component Architecture", project: "Build a task management UI with React" },
                    { title: "Node.js & Express.js", project: "Build a REST API for the task manager" },
                    { title: "Database Design (MongoDB, MySQL)", project: "Design the schema for a product catalog" },
                    { title: "API Development & Integration", project: "Connect your frontend to the backend API" },
                    { title: "Version Control with Git" },
                    { title: "TypeScript Fundamentals", project: "Add TypeScript to your existing project" },
                    { title: "Advanced React: Hooks & Context API", project: "Refactor your app with advanced React patterns" },
                    { title: "Payment Integration (SSLCommerz)", project: "Add payments to your full-stack application" },
                    { title: "Testing (Jest & Supertest)", project: "Write unit and integration tests for your API" },
                    { title: "Docker & Basic DevOps", project: "Containerize and deploy your app with Docker" },
                    { title: "Internship (Real Client Project)" },
                ],
            },
        ],
    },

    // 3 ─ Graphic Design
    {
        slug: "graphic-design",
        title: "Graphic Design",
        description: "Create stunning visual designs using industry-standard tools and design principles.",
        detailedDescription: "Develop your creative skills in visual communication, branding, and digital design. Master Adobe Creative Suite and learn design principles that make your work stand out.",
        tools: ["Adobe Photoshop", "Adobe Illustrator", "Adobe InDesign", "Canva Pro"],
        prerequisites: "Creative mindset and basic computer skills",
        certification: "Professional Graphic Designer Certificate",
        published: true,
        packages: [
            {
                name: "Foundation",
                tier: "certificate",
                duration: "6 months",
                totalFee: 12000,
                offlineTotalFee: 18000,
                registrationFee: 4000,
                installmentAmount: 2000,
                installmentCount: 4,
                currency: "BDT",
                scheduleType: "both",
                isPopular: false,
                isJobReady: false,
                outcomeStatement: "Build a professional design portfolio with 4 completed projects across branding, print, and digital media",
                idealForThisPackage: "Creative beginners and hobbyists who want to turn their eye for design into a marketable skill or freelance income",
                deliverables: [
                    "Complete brand identity for a mock client",
                    "Print-ready brochure design",
                    "Social media graphics set (10 posts)",
                    "Documented portfolio on Behance",
                    "Professional Graphic Designer Certificate",
                ],
                modules: [
                    { title: "Design Principles & Theory" },
                    { title: "Adobe Photoshop Mastery", project: "Create a professional photo retouching & composite" },
                    { title: "Adobe Illustrator Techniques", project: "Design a vector logo for a mock brand" },
                    { title: "Brand Identity Design", project: "Build a complete brand kit (logo, colors, fonts, and usage guide)" },
                    { title: "Print & Digital Media Design", project: "Design a print-ready tri-fold brochure" },
                    { title: "Portfolio Creation", project: "Publish your 4-piece portfolio to Behance" },
                ],
            },
            {
                name: "Job-Ready Professional",
                tier: "job-ready",
                duration: "1 year",
                totalFee: 18000,
                offlineTotalFee: 25000,
                registrationFee: 6000,
                installmentAmount: 2000,
                installmentCount: 6,
                currency: "BDT",
                scheduleType: "both",
                isPopular: true,
                isJobReady: true,
                outcomeStatement: "Graduate with a client-ready portfolio of 8+ polished projects, motion design skills, and a clear path into studio or agency work",
                idealForThisPackage: "Serious creatives who want to work at a design agency, start a design business, or command high-value freelance rates",
                deliverables: [
                    "8+ portfolio pieces across branding, digital, and motion",
                    "Motion graphics & basic video editing skills",
                    "Complete brand identity from a real client (internship)",
                    "Job placement support & agency referral",
                    "1-year Professional Graphic Designer Certificate",
                ],
                modules: [
                    { title: "Design Principles & Theory" },
                    { title: "Adobe Photoshop Mastery", project: "Create a professional photo retouching & composite" },
                    { title: "Adobe Illustrator Techniques", project: "Design a vector logo for a mock brand" },
                    { title: "Brand Identity Design", project: "Build a complete brand kit (logo, colors, fonts, and usage guide)" },
                    { title: "Print & Digital Media Design", project: "Design a print-ready tri-fold brochure" },
                    { title: "Portfolio Creation", project: "Publish your 4-piece portfolio to Behance" },
                    { title: "Typography Mastery & Editorial Design", project: "Design a 4-page magazine spread" },
                    { title: "Motion Graphics with Adobe After Effects", project: "Create a 15-second animated brand intro" },
                    { title: "Social Media & Content Design Systems", project: "Build a reusable social media template kit" },
                    { title: "Packaging & Merchandise Design", project: "Design product packaging for a mock brand" },
                    { title: "Client Presentation & Freelance Pricing" },
                    { title: "Internship (Real Client Project)" },
                ],
            },
        ],
    },

    // 4 ─ UI-UX Design
    {
        slug: "ui-ux-design",
        title: "UI-UX Design",
        description: "Design intuitive user interfaces and create exceptional user experiences.",
        detailedDescription: "Learn to create user-centered designs that are both beautiful and functional. Master user research, wireframing, prototyping, and usability testing.",
        tools: ["Figma", "Adobe XD", "Sketch", "InVision", "Miro"],
        prerequisites: "Basic design knowledge helpful",
        certification: "UI/UX Designer Professional Certificate",
        published: true,
        packages: [
            {
                name: "Foundation",
                tier: "certificate",
                duration: "6 months",
                totalFee: 12000,
                offlineTotalFee: 18000,
                registrationFee: 4000,
                installmentAmount: 2000,
                installmentCount: 4,
                currency: "BDT",
                scheduleType: "both",
                isPopular: false,
                isJobReady: false,
                outcomeStatement: "Complete a full end-to-end UX design process — from user research to a tested, interactive Figma prototype — for a real product brief",
                idealForThisPackage: "Aspiring UX/UI designers, developers who want to understand design thinking, and career-changers entering the product design field",
                deliverables: [
                    "End-to-end UX case study (research → prototype → test)",
                    "Interactive Figma prototype with 10+ screens",
                    "Usability test report with documented findings",
                    "Behance or personal design portfolio",
                    "UI/UX Designer Professional Certificate",
                ],
                modules: [
                    { title: "User Research & Analysis", project: "Conduct 3 user interviews and synthesize a research report" },
                    { title: "Wireframing & Prototyping", project: "Build low-fidelity wireframes for a mobile app" },
                    { title: "UI Design Principles", project: "Design 5 high-fidelity UI screens in Figma" },
                    { title: "Interaction Design", project: "Add micro-interactions and transitions to your prototype" },
                    { title: "Usability Testing", project: "Run a moderated usability test and document findings" },
                    { title: "Design Systems", project: "Build a reusable component library in Figma" },
                ],
            },
            {
                name: "Job-Ready Professional",
                tier: "job-ready",
                duration: "1 year",
                totalFee: 18000,
                offlineTotalFee: 25000,
                registrationFee: 6000,
                installmentAmount: 2000,
                installmentCount: 6,
                currency: "BDT",
                scheduleType: "both",
                isPopular: true,
                isJobReady: true,
                outcomeStatement: "Graduate with 3 detailed UX case studies, proficiency across the full product design stack, and a job-ready portfolio that meets industry hiring standards",
                idealForThisPackage: "Anyone targeting a product designer or UX researcher role at a software company or digital agency",
                deliverables: [
                    "3 complete UX case studies with documented process",
                    "Design system with tokens, components & documentation",
                    "Real product internship contribution",
                    "Job placement support & portfolio review",
                    "1-year UI/UX Designer Certificate",
                ],
                modules: [
                    { title: "User Research & Analysis", project: "Conduct 3 user interviews and synthesize a research report" },
                    { title: "Wireframing & Prototyping", project: "Build low-fidelity wireframes for a mobile app" },
                    { title: "UI Design Principles", project: "Design 5 high-fidelity UI screens in Figma" },
                    { title: "Interaction Design", project: "Add micro-interactions and transitions to your prototype" },
                    { title: "Usability Testing", project: "Run a moderated usability test and document findings" },
                    { title: "Design Systems", project: "Build a reusable component library in Figma" },
                    { title: "Advanced Figma: Variables & Design Tokens", project: "Implement a light/dark mode design system" },
                    { title: "UX Writing & Microcopy" },
                    { title: "Mobile App Design Patterns", project: "Design a complete mobile app from brief to prototype" },
                    { title: "Analytics-Driven UX (Hotjar, GA4)", project: "Audit an existing product and propose data-backed improvements" },
                    { title: "UX Portfolio & Case Study Writing" },
                    { title: "Internship (Real Product Design Project)" },
                ],
            },
        ],
    },

    // 5 ─ Digital Marketing
    {
        slug: "digital-marketing",
        title: "Digital Marketing",
        description: "Learn digital marketing strategies, SEO, social media marketing, and analytics.",
        detailedDescription: "Master the digital marketing landscape with hands-on experience in SEO, social media marketing, content marketing, PPC advertising, and analytics.",
        tools: ["Google Analytics", "Google Ads", "Facebook Business Manager", "SEMrush"],
        prerequisites: "Basic internet and social media knowledge",
        certification: "Digital Marketing Professional Certificate",
        published: true,
        packages: [
            {
                name: "Foundation",
                tier: "certificate",
                duration: "6 months",
                totalFee: 12000,
                offlineTotalFee: 18000,
                registrationFee: 4000,
                installmentAmount: 2000,
                installmentCount: 4,
                currency: "BDT",
                scheduleType: "both",
                isPopular: false,
                isJobReady: false,
                outcomeStatement: "Run live paid and organic campaigns, measure real ROI, and build a results portfolio you can show to employers or clients",
                idealForThisPackage: "Business owners, career-changers, and anyone who wants practical, measurable digital marketing skills",
                deliverables: [
                    "SEO-optimized blog or landing page (live)",
                    "Documented Google Ads campaign with performance data",
                    "Facebook/Instagram ad campaign report",
                    "GA4 setup & custom reporting dashboard",
                    "Digital Marketing Professional Certificate",
                ],
                modules: [
                    { title: "Digital Marketing Fundamentals" },
                    { title: "Search Engine Optimization (SEO)", project: "Rank a test page in Google for a low-competition keyword" },
                    { title: "Social Media Marketing", project: "Build a 30-day content calendar for a real brand" },
                    { title: "Content Marketing Strategy" },
                    { title: "Google Ads & Facebook Ads", project: "Run a live ৳500 ad campaign — Webtricker covers the ad spend — and submit a performance report" },
                    { title: "Analytics & Performance Tracking", project: "Set up GA4 with custom event tracking on a live site" },
                ],
            },
            {
                name: "Job-Ready Professional",
                tier: "job-ready",
                duration: "1 year",
                totalFee: 18000,
                offlineTotalFee: 25000,
                registrationFee: 6000,
                installmentAmount: 2000,
                installmentCount: 6,
                currency: "BDT",
                scheduleType: "both",
                isPopular: true,
                isJobReady: true,
                outcomeStatement: "Graduate with verifiable campaign case studies, two international certifications, and a clear path into a marketing agency or in-house role",
                idealForThisPackage: "Anyone targeting a career at a marketing agency, e-commerce brand, or as an independent consultant",
                deliverables: [
                    "3+ campaign case studies with real performance data",
                    "Google Ads & Analytics certifications",
                    "Meta Blueprint certification",
                    "Full marketing strategy for a real brand",
                    "Internship with a live client",
                    "Job placement support",
                    "1-year Digital Marketing Certificate",
                ],
                modules: [
                    { title: "Digital Marketing Fundamentals" },
                    { title: "Search Engine Optimization (SEO)", project: "Rank a test page in Google for a low-competition keyword" },
                    { title: "Social Media Marketing", project: "Build a 30-day content calendar for a real brand" },
                    { title: "Content Marketing Strategy" },
                    { title: "Google Ads & Facebook Ads", project: "Run a live ৳500 ad campaign — Webtricker covers the ad spend — and submit a performance report" },
                    { title: "Analytics & Performance Tracking", project: "Set up GA4 with custom event tracking on a live site" },
                    { title: "Advanced SEO: Technical & Link Building" },
                    { title: "E-Commerce Marketing Strategy", project: "Build a full marketing funnel for a Shopify store" },
                    { title: "Influencer & Affiliate Marketing" },
                    { title: "Marketing Automation & Email Campaigns", project: "Build an automated email drip sequence in Mailchimp" },
                    { title: "Campaign Case Study & Portfolio Review" },
                    { title: "Internship (Real Client Campaign)" },
                ],
            },
        ],
    },

    // 6 ─ CMS Development
    {
        slug: "cms-development",
        title: "CMS Development",
        description: "Build and customize content management systems using popular platforms.",
        detailedDescription: "Learn to develop and customize content management systems. Master WordPress, Drupal, and modern headless CMS solutions for dynamic website development.",
        tools: ["WordPress", "PHP", "MySQL", "Strapi", "VS Code"],
        prerequisites: "Basic web development knowledge",
        certification: "CMS Developer Certificate",
        published: true,
        packages: [
            {
                name: "Foundation",
                tier: "certificate",
                duration: "6 months",
                totalFee: 12000,
                offlineTotalFee: 18000,
                registrationFee: 4000,
                installmentAmount: 2000,
                installmentCount: 4,
                currency: "BDT",
                scheduleType: "both",
                isPopular: false,
                isJobReady: false,
                outcomeStatement: "Build and launch 2 fully functional websites on WordPress — one business site and one e-commerce store — and be ready to take on real client projects",
                idealForThisPackage: "Freelancers, small business owners, and developers who want to build and manage websites professionally using popular CMS platforms",
                deliverables: [
                    "5-page business website built on WordPress",
                    "Working WooCommerce e-commerce store",
                    "Custom WordPress theme built from scratch",
                    "2 custom plugins built and documented",
                    "CMS Developer Certificate",
                ],
                modules: [
                    { title: "CMS Fundamentals" },
                    { title: "WordPress Development", project: "Build a 5-page business website in WordPress" },
                    { title: "Custom Theme Creation", project: "Build a custom WordPress theme from a Figma mockup" },
                    { title: "Plugin Development", project: "Build a custom contact form plugin with database storage" },
                    { title: "Headless CMS (Strapi, Contentful)", project: "Build a blog with a headless CMS and Next.js frontend" },
                    { title: "E-commerce Integration", project: "Set up a WooCommerce store with 10 products and payment gateway" },
                ],
            },
            {
                name: "Job-Ready Professional",
                tier: "job-ready",
                duration: "1 year",
                totalFee: 18000,
                offlineTotalFee: 25000,
                registrationFee: 6000,
                installmentAmount: 2000,
                installmentCount: 6,
                currency: "BDT",
                scheduleType: "both",
                isPopular: true,
                isJobReady: true,
                outcomeStatement: "Graduate capable of delivering complex WordPress builds for clients, with real project experience and the skills to command professional rates",
                idealForThisPackage: "Developers who want to freelance professionally, work at a web agency, or manage complex multi-client WordPress environments",
                deliverables: [
                    "3 client-quality CMS-powered websites",
                    "Custom Gutenberg block library",
                    "Performance-optimized WooCommerce store",
                    "Real client internship project",
                    "Job placement support",
                    "1-year CMS Developer Certificate",
                ],
                modules: [
                    { title: "CMS Fundamentals" },
                    { title: "WordPress Development", project: "Build a 5-page business website in WordPress" },
                    { title: "Custom Theme Creation", project: "Build a custom WordPress theme from a Figma mockup" },
                    { title: "Plugin Development", project: "Build a custom contact form plugin with database storage" },
                    { title: "Headless CMS (Strapi, Contentful)", project: "Build a blog with a headless CMS and Next.js frontend" },
                    { title: "E-commerce Integration", project: "Set up a WooCommerce store with 10 products and payment gateway" },
                    { title: "Advanced WordPress: Gutenberg & Custom Blocks", project: "Build a custom Gutenberg block library for a client theme" },
                    { title: "WordPress Performance & Security Hardening", project: "Audit and optimize an existing site for Core Web Vitals" },
                    { title: "WooCommerce Advanced: Subscriptions & Multi-vendor" },
                    { title: "REST API & WordPress Headless Architecture", project: "Build a decoupled WordPress + Next.js site" },
                    { title: "Client Management & Project Delivery" },
                    { title: "Internship (Real Client CMS Project)" },
                ],
            },
        ],
    },

    // 7 ─ MERN Stack Development
    {
        slug: "mern-stack-development",
        title: "MERN Stack Development",
        description: "Full-stack development with MongoDB, Express.js, React, and Node.js.",
        detailedDescription: "Become proficient in the MERN stack and build modern, scalable web applications. Learn MongoDB, Express.js, React, and Node.js with real-world projects.",
        tools: ["MongoDB", "Express.js", "React", "Node.js", "VS Code"],
        prerequisites: "JavaScript fundamentals required",
        certification: "MERN Stack Developer Certificate",
        published: true,
        packages: [
            {
                name: "Foundation",
                tier: "certificate",
                duration: "6 months",
                totalFee: 12000,
                offlineTotalFee: 18000,
                registrationFee: 4000,
                installmentAmount: 2000,
                installmentCount: 4,
                currency: "BDT",
                scheduleType: "both",
                isPopular: false,
                isJobReady: false,
                outcomeStatement: "Build and deploy 2 full-stack web apps — a CRUD blog and an e-commerce prototype — using the MERN stack",
                idealForThisPackage: "Beginners with basic JavaScript knowledge who want to build real web apps using the most in-demand stack within 6 months",
                deliverables: [
                    "Deployed blog app with user authentication & full CRUD",
                    "E-commerce frontend with cart & checkout flow",
                    "REST API with JWT authentication",
                    "GitHub portfolio with 2 public MERN projects",
                    "Full-Stack Developer Certificate",
                ],
                modules: [
                    { title: "MongoDB Database Design", project: "Design and seed the schema for a blog app" },
                    { title: "Express.js Server Development", project: "Build a REST API with full CRUD operations" },
                    { title: "React.js Frontend Development", project: "Build the frontend UI for your blog app" },
                    { title: "Node.js Backend Programming", project: "Add user auth and protected routes to the blog" },
                    { title: "Authentication & Authorization" },
                    { title: "Deployment & DevOps", project: "Deploy your MERN app to Vercel + MongoDB Atlas" },
                ],
            },
            {
                name: "Job-Ready Professional",
                tier: "job-ready",
                duration: "1 year",
                totalFee: 18000,
                offlineTotalFee: 25000,
                registrationFee: 6000,
                installmentAmount: 2000,
                installmentCount: 6,
                currency: "BDT",
                scheduleType: "both",
                isPopular: true,
                isJobReady: true,
                outcomeStatement: "Graduate with a deployed, production-grade SaaS project in your portfolio and real internship experience on your CV",
                idealForThisPackage: "Ambitious learners targeting a junior developer role or a freelance career within 12 months",
                deliverables: [
                    "1 live, production-grade SaaS application",
                    "Full auth, payments & admin panel implemented",
                    "Docker + CI/CD pipeline configured",
                    "Real internship project contribution",
                    "Job placement support",
                    "1-year MERN Stack Certificate",
                ],
                modules: [
                    { title: "MongoDB Database Design", project: "Design and seed the schema for a blog app" },
                    { title: "Express.js Server Development", project: "Build a REST API with full CRUD operations" },
                    { title: "React.js Frontend Development", project: "Build the frontend UI for your blog app" },
                    { title: "Node.js Backend Programming", project: "Add user auth and protected routes to the blog" },
                    { title: "Authentication & Authorization" },
                    { title: "Deployment & DevOps", project: "Deploy your MERN app to Vercel + MongoDB Atlas" },
                    { title: "TypeScript for Full-Stack Developers", project: "Migrate your blog app to TypeScript" },
                    { title: "State Management (Redux / Zustand)", project: "Add global state to your SaaS app" },
                    { title: "Payment Integration (SSLCommerz)", project: "Implement checkout in your SaaS application" },
                    { title: "Testing & Quality Assurance" },
                    { title: "Docker & CI/CD Basics", project: "Containerize your app and set up GitHub Actions" },
                    { title: "Internship (Real Client Project)" },
                ],
            },
        ],
    },

    // 8 ─ Basic Computer and AI Tools Training
    {
        slug: "basic-computer-and-ai-tools-training",
        title: "Basic Computer and AI Tools Training",
        description: "Master essential computer skills and modern AI tools for enhanced productivity.",
        detailedDescription: "Build foundational computer skills and learn to leverage AI tools for increased productivity. Perfect for beginners looking to enhance their digital literacy.",
        tools: ["Windows/Mac OS", "ChatGPT", "Google Workspace", "AI Writing Tools"],
        prerequisites: "No prior experience required",
        certification: "Digital Literacy Certificate",
        published: true,
        packages: [
            {
                name: "Foundation",
                tier: "certificate",
                duration: "6 months",
                totalFee: 12000,
                offlineTotalFee: 18000,
                registrationFee: 4000,
                installmentAmount: 2000,
                installmentCount: 4,
                currency: "BDT",
                scheduleType: "both",
                isPopular: false,
                isJobReady: false,
                outcomeStatement: "Use AI tools confidently to complete real office and creative tasks faster, and help your team or business get more done in less time",
                idealForThisPackage: "Complete beginners, office workers, freelancers, and small business owners who want to work smarter using modern digital tools",
                deliverables: [
                    "Personal productivity workflow using AI tools (documented)",
                    "AI-generated content portfolio (writing, images, summaries)",
                    "AI tool comparison guide for your field",
                    "Digital Literacy Certificate",
                ],
                modules: [
                    { title: "Computer Fundamentals" },
                    { title: "Internet & Email Basics" },
                    { title: "File Management & Organization", project: "Build a structured digital file system and cloud backup workflow" },
                    { title: "AI Tools (ChatGPT, Claude, Gemini)", project: "Use AI to write, summarize, and research a real topic of your choice" },
                    { title: "Productivity AI Applications", project: "Automate a repetitive task using AI tools (content, scheduling, or data)" },
                    { title: "Digital Security & Privacy" },
                ],
            },
            {
                name: "Job-Ready Professional",
                tier: "job-ready",
                duration: "1 year",
                totalFee: 18000,
                offlineTotalFee: 25000,
                registrationFee: 6000,
                installmentAmount: 2000,
                installmentCount: 6,
                currency: "BDT",
                scheduleType: "both",
                isPopular: true,
                isJobReady: true,
                outcomeStatement: "Graduate as a confident AI-powered digital professional who can build AI workflows, train others, and help any organization adopt modern tools",
                idealForThisPackage: "Team leads, entrepreneurs, and professionals who want to become the AI champion in their organization",
                deliverables: [
                    "Personal AI-powered workflow toolkit (documented)",
                    "AI literacy training presentation for a team",
                    "No-code automation built with AI tools",
                    "Real internship project contribution",
                    "Job placement support",
                    "1-year AI Tools & Digital Productivity Certificate",
                ],
                modules: [
                    { title: "Computer Fundamentals" },
                    { title: "Internet & Email Basics" },
                    { title: "File Management & Organization", project: "Build a structured digital file system and cloud backup workflow" },
                    { title: "AI Tools (ChatGPT, Claude, Gemini)", project: "Use AI to write, summarize, and research a real topic of your choice" },
                    { title: "Productivity AI Applications", project: "Automate a repetitive task using AI tools (content, scheduling, or data)" },
                    { title: "Digital Security & Privacy" },
                    { title: "No-Code App Building with AI (Bubble, Glide)", project: "Build a simple no-code app for a real use case" },
                    { title: "AI for Content Creation (Canva AI, Midjourney)", project: "Design a complete social media content pack using AI tools" },
                    { title: "AI for Research & Knowledge Management", project: "Build an AI-powered research and knowledge base in Notion AI" },
                    { title: "Automation with AI (Zapier, Make)", project: "Build a 3-step automation that saves at least 2 hours per week" },
                    { title: "Teaching Digital Literacy: Training Others" },
                    { title: "Internship (Real Organization Project)" },
                ],
            },
        ],
    },

    // 9 ─ Microsoft Office Tools Training
    {
        slug: "microsoft-office-tools-training",
        title: "Microsoft Office Tools Training",
        description: "Master Microsoft Office suite for professional productivity and efficiency.",
        detailedDescription: "Become proficient in Microsoft Office applications including Word, Excel, PowerPoint, and Outlook. Learn advanced features and automation techniques.",
        tools: ["Microsoft Word", "Excel", "PowerPoint", "Outlook", "Access"],
        prerequisites: "Basic computer knowledge",
        certification: "Microsoft Office Specialist Certificate",
        published: true,
        packages: [
            {
                name: "Foundation",
                tier: "certificate",
                duration: "6 months",
                totalFee: 12000,
                offlineTotalFee: 18000,
                registrationFee: 4000,
                installmentAmount: 2000,
                installmentCount: 4,
                currency: "BDT",
                scheduleType: "both",
                isPopular: false,
                isJobReady: false,
                outcomeStatement: "Work confidently with Word, Excel, and PowerPoint at a professional level and handle real office tasks without needing help",
                idealForThisPackage: "Job seekers, administrative staff, students, and anyone who needs strong Microsoft Office skills for their career",
                deliverables: [
                    "Professional report formatted in Microsoft Word",
                    "Excel budget tracker with formulas, charts & pivot tables",
                    "Polished PowerPoint presentation (20+ slides)",
                    "Microsoft Office Specialist Certificate",
                ],
                modules: [
                    { title: "Microsoft Word Advanced", project: "Create a formatted 10-page professional report with styles and table of contents" },
                    { title: "Excel Formulas & Functions", project: "Build a monthly budget tracker with pivot tables and charts" },
                    { title: "PowerPoint Presentation Design", project: "Design a polished 20-slide company presentation" },
                    { title: "Outlook Email Management" },
                    { title: "Access Database Basics", project: "Build a simple inventory tracking database in Access" },
                    { title: "Office Integration & Automation", project: "Create a mail-merge letter campaign using Word + Excel" },
                ],
            },
            {
                name: "Job-Ready Professional",
                tier: "job-ready",
                duration: "1 year",
                totalFee: 18000,
                offlineTotalFee: 25000,
                registrationFee: 6000,
                installmentAmount: 2000,
                installmentCount: 6,
                currency: "BDT",
                scheduleType: "both",
                isPopular: true,
                isJobReady: true,
                outcomeStatement: "Master advanced Excel, data visualization, and Office automation — skills that get you promoted and make you the most productive person on any team",
                idealForThisPackage: "Professionals, accountants, analysts, and managers who want to move from basic to advanced Office skills and use automation to work significantly faster",
                deliverables: [
                    "Advanced Excel financial model with scenario analysis",
                    "Interactive Power BI dashboard connected to live data",
                    "VBA macro automating a real repetitive office task",
                    "Real internship project contribution",
                    "Job placement support",
                    "1-year Microsoft Office Professional Certificate",
                ],
                modules: [
                    { title: "Microsoft Word Advanced", project: "Create a formatted 10-page professional report with styles and table of contents" },
                    { title: "Excel Formulas & Functions", project: "Build a monthly budget tracker with pivot tables and charts" },
                    { title: "PowerPoint Presentation Design", project: "Design a polished 20-slide company presentation" },
                    { title: "Outlook Email Management" },
                    { title: "Access Database Basics", project: "Build a simple inventory tracking database in Access" },
                    { title: "Office Integration & Automation", project: "Create a mail-merge letter campaign using Word + Excel" },
                    { title: "Advanced Excel: Power Query & Power Pivot", project: "Build a sales analysis dashboard with Power Query" },
                    { title: "Data Visualization with Power BI", project: "Build an interactive Power BI report from a real dataset" },
                    { title: "Excel VBA & Macro Automation", project: "Write a VBA macro that automates a monthly report" },
                    { title: "Advanced PowerPoint: Presentation Design Systems", project: "Create a branded template system for a mock company" },
                    { title: "SharePoint & Microsoft Teams for Organizations" },
                    { title: "Internship (Real Office Project)" },
                ],
            },
        ],
    },
];

export const POST = async (req: NextRequest) => {
    try {
        await dbConnect();
        await verifyAdmin(req);

        const existing = await Training.countDocuments();
        if (existing > 0) {
            return NextResponse.json(
                { success: false, message: `Seed skipped — ${existing} courses already exist. Delete them first to re-seed.` },
                { status: 409 }
            );
        }

        const inserted = await Training.insertMany(seedCourses);
        return NextResponse.json(
            { success: true, message: `Seeded ${inserted.length} training courses.`, count: inserted.length },
            { status: 201 }
        );
    } catch (error) {
        console.error("Error seeding training courses:", error);
        return NextResponse.json({ success: false, message: "Internal Server Error" }, { status: 500 });
    }
};
